version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: standup_user
      POSTGRES_PASSWORD: standup_pass
      POSTGRES_DB: standup_db
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://standup_user:standup_pass@db:5432/standup_db
      NODE_ENV: development
      NEXTAUTH_URL: http://localhost:5777
      NEXT_PUBLIC_APP_URL: http://localhost:5777
    depends_on:
      - db
    ports:
      - "5777:3000"

volumes:
  postgres_data:
